### ISSUE TITLE
BUG : impossible de se désinscrire dans ‘AIDER’

### ISSUE THREAD

**Issue by Fsardas** [geleouet/cageot#8]
Si un user s'inscrit à AIDER, il ne peut plus se désinscrire (il a l'impression que oui, mais en fait non :))

**Comment by geleouet** [comment]
java.lang.IllegalArgumentException: argument is null or empty; this is forbidden on this call to `bindList`
	at org.jdbi.v3.core.statement.EmptyHandling$4.accept(EmptyHandling.java:61)
	at org.jdbi.v3.core.statement.EmptyHandling$4.accept(EmptyHandling.java:58)
	at org.jdbi.v3.core.statement.SqlStatement.bindList(SqlStatement.java:1410)
	at org.jdbi.v3.core.statement.SqlStatement.bindList(SqlStatement.java:1352)
	at org.jdbi.v3.core.statement.SqlStatement.bindList(SqlStatement.java:1338)
	at me.egaetan.store.task.TaskDao.lambda$6(TaskDao.java:70)

**Comment by Fsardas** [comment]
Non, ça ne marche toujours pas

**Comment by Fsardas** [comment]
Bravo ça marche faudra juste penser à retirer le bouton de test gg
